import { JSX } from 'react';

import FooterWrapper from '@/components/footer/FooterWrapper';
import HeaderWrapper from '@/components/header/HeaderWrapper';

import '../styles/globals.css';
import '../styles/normalize.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body>
        <HeaderWrapper />
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
