import { JSX } from 'react';

import AsideMainMenu from '@/components/AsideMainMenu';
import AsideProductSearch from '@/components/AsideProductSearch';
import Blackout from '@/components/Blackout';
import AsideCart from '@/components/cart/AsideCart';
import FooterWrapper from '@/components/footer/FooterWrapper';
import HeaderWrapper from '@/components/header/HeaderWrapper';
import { StoreProviders } from '@/store/StoreProvaider';

import '../styles/globals.css';
// import '../styles/normalize.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body>
        <StoreProviders>
          <HeaderWrapper />
          {children}
          <FooterWrapper />
          <AsideCart />
          <AsideMainMenu />
          <AsideProductSearch />
          <Blackout />
        </StoreProviders>
      </body>
    </html>
  );
}
