version: '3.8'

services:
  backend:
    container_name: mstore-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.app
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    networks:
      - mstore
    ports:
      - '${API_PORT}:${API_PORT}'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.app
    container_name: mstore-frontend
    environment:
      - NODE_ENV=production
    command: ['npm', 'run', 'start']
    networks:
      - mstore
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'   

networks:
  mstore:
    driver: bridge